### ISSUE TITLE
Change minimum php requirement from 7.2 => 7.4

### ISSUE THREAD

**Issue by dominikzogg** [psr7-sessions/storageless-mezzio-integration#4]
@Ocramius 

I would recommend to have version 1.0 with the current code base (fixes where needed of course).

Then if possible create a version,1.1 if the BC's of psr7-sessions/storageless 5.0 => 7.1 aren't relevant for this code, or a 2.0 if they are.

**Comment by Ocramius** [comment]
IMO we should release with at least 7.3 - 7.2 is going EOL now-ish

**Comment by dominikzogg** [comment]
Ok 7.4 then, cause even 6.0 of the psr7-sessions/storageless needs php 7.4

**Comment by dominikzogg** [comment]
Will do it.

**Comment by dominikzogg** [comment]
https://github.com/psr7-sessions/storageless-mezzio-integration/pull/5
