### ISSUE TITLE
Register library in packagist and scrutinizer

### ISSUE THREAD

**Issue by dominikzogg** [psr7-sessions/storageless-mezzio-integration#6]
The library is not registred in
- packagist
- scrutinizer

**Comment by Ocramius** [comment]
Scrutinizer can probably be dropped - doing packagist now 👍

**Comment by Ocramius** [comment]
Packagist registered

**Comment by dominikzogg** [comment]
@Ocramius migrate to coveralls for coverage?

**Comment by dominikzogg** [comment]
i mean its 100% anyway, cause infection, but not everyone is aware about you're quality standards ;-)

**Comment by Ocramius** [comment]
We can use stryker for mutation tests (for the badge) - less effort than scrutinizer

**Comment by dominikzogg** [comment]
@Ocramius do you have a library in mind using mutation tests triggered by travis?

**Comment by Ocramius** [comment]
Infection supports the badge natively

**Comment by dominikzogg** [comment]
@Ocramius do you generate the token and add it to travis as environment variable? i would adapt the code

**Comment by Ocramius** [comment]
Wish I could, but I think I broke the pagination in stryker due to too many organisations :D 

For now, I endorse just dropping the badges.

**Comment by dominikzogg** [comment]
@Ocramius if i get the access for psr7-sessions within stryker, i can add the token in travis

**Comment by Ocramius** [comment]
Done

**Comment by dominikzogg** [comment]
Key added, i'll check if it works

**Comment by Ocramius** [comment]
Closing here, since packagist now has a published package for this 👍
