### ISSUE TITLE
Release V1?

### ISSUE THREAD

**Issue by dominikzogg** [psr7-sessions/storageless-mezzio-integration#8]
Hello @Ocramius 

Any objections to prepare a V1 release?

**Comment by Ocramius** [comment]
We just need to set up release automation to do that: already done in the
main storageless repo

**Comment by dominikzogg** [comment]
@Ocramius k, have no idea todo so, can you link a related file or documentation?

**Comment by Ocramius** [comment]
I think it's only a matter of copying over https://github.com/psr7-sessions/storageless/blob/7.3.x/.github/workflows/release-on-milestone-closed.yml here.

Documentation for how the release tool works is @ https://github.com/laminas/automatic-releases - it does a release whenever you close an associated milestone, and requires the branch to be named `1.0.x`.
